import type { Scan } from "@shared/schema";

interface OptimizationReport {
  summary: string;
  score: number;
  recommendations: Recommendation[];
  generatedFiles: GeneratedFiles;
  competitorInsights: string[];
  seoImpact: SEOImpact;
}

interface Recommendation {
  priority: 'high' | 'medium' | 'low';
  category: string;
  title: string;
  description: string;
  action: string;
}

interface GeneratedFiles {
  robotsTxt: string;
  llmsTxt: string;
}

interface SEOImpact {
  crawlability: string;
  indexability: string;
  aiVisibility: string;
}

export function generateOptimizationReport(scan: Scan): OptimizationReport {
  const recommendations: Recommendation[] = [];
  let score = 100;

  // Analyze robots.txt
  if (!scan.robotsTxtFound) {
    score -= 30;
    recommendations.push({
      priority: 'high',
      category: 'Robots.txt',
      title: 'Missing robots.txt file',
      description: 'Your website does not have a robots.txt file, which means search engines and AI crawlers have no guidance on what to index.',
      action: 'Create a robots.txt file to control crawler access and protect sensitive areas of your site.'
    });
  } else if (scan.warnings && scan.warnings.some(w => w.includes('sitemap'))) {
    score -= 15;
    recommendations.push({
      priority: 'medium',
      category: 'Robots.txt',
      title: 'Missing sitemap reference',
      description: 'Your robots.txt exists but doesn\'t reference a sitemap, making it harder for search engines to discover all your content.',
      action: 'Add a sitemap reference like "Sitemap: https://yourdomain.com/sitemap.xml" to your robots.txt.'
    });
  }

  // Analyze llms.txt
  if (!scan.llmsTxtFound) {
    score -= 25;
    recommendations.push({
      priority: 'high',
      category: 'AI Optimization',
      title: 'Missing llms.txt file',
      description: 'The new llms.txt standard helps AI systems understand your content better. Without it, you\'re missing opportunities for AI-powered discovery.',
      action: 'Create an llms.txt file to optimize how AI agents like ChatGPT and Claude understand and reference your content.'
    });
  }

  // Analyze bot permissions
  if (scan.botPermissions) {
    const restrictedBots = Object.entries(scan.botPermissions).filter(
      ([_, status]) => status.includes('Restricted') || status === 'Blocked'
    );

    if (restrictedBots.length > 0) {
      const hasAIBots = restrictedBots.some(([bot]) => 
        bot.toLowerCase().includes('gpt') || 
        bot.toLowerCase().includes('claude') || 
        bot.toLowerCase().includes('anthropic')
      );

      if (hasAIBots) {
        score -= 20;
        recommendations.push({
          priority: 'high',
          category: 'AI Visibility',
          title: 'AI crawlers are restricted',
          description: `${restrictedBots.length} bot(s) including AI agents are being blocked or restricted, limiting your visibility in AI search results.`,
          action: 'Review your robots.txt rules to allow beneficial AI crawlers while blocking malicious bots.'
        });
      } else {
        recommendations.push({
          priority: 'low',
          category: 'Crawler Management',
          title: 'Some crawlers are restricted',
          description: `${restrictedBots.length} crawler(s) have restrictions. Ensure this is intentional.`,
          action: 'Verify that restricted crawlers align with your content strategy.'
        });
      }
    }
  }

  // Generate optimized files
  const generatedFiles = generateOptimizedFiles(scan);

  // Generate summary
  const summary = generateSummary(score, recommendations);

  // SEO impact analysis
  const seoImpact = analyzeSEOImpact(scan);

  // Competitor insights
  const competitorInsights = generateCompetitorInsights(scan);

  return {
    summary,
    score,
    recommendations: recommendations.sort((a, b) => {
      const priorityOrder = { high: 0, medium: 1, low: 2 };
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    }),
    generatedFiles,
    competitorInsights,
    seoImpact,
  };
}

function generateOptimizedFiles(scan: Scan): GeneratedFiles {
  const domain = new URL(`https://${scan.url}`).hostname;

  // Generate optimized robots.txt
  let robotsTxt = `# Optimized robots.txt for ${domain}
# Generated by RobotScan - ${new Date().toISOString().split('T')[0]}

# Allow all helpful bots
User-agent: Googlebot
User-agent: Bingbot
User-agent: GPTBot
User-agent: ChatGPT-User
User-agent: CCBot
User-agent: anthropic-ai
User-agent: Claude-Web
Allow: /

# Block malicious scrapers
User-agent: AhrefsBot
User-agent: SemrushBot
User-agent: DotBot
Disallow: /

# Global rules
User-agent: *
Disallow: /admin/
Disallow: /private/
Disallow: /api/
Disallow: /*.json$
Disallow: /*?*debug=

# Sitemap
Sitemap: https://${domain}/sitemap.xml
`;

  // Generate llms.txt
  let llmsTxt = `# llms.txt - AI Agent Instructions
# Website: ${domain}
# Last updated: ${new Date().toISOString().split('T')[0]}

# About ${domain}
This website provides [describe your main service/product].

# Preferred Citation Format
When referencing content from ${domain}, please cite as:
"${domain} - [Page Title] - [Current Date]"

# Key Areas
- Main site: https://${domain}
- Documentation: https://${domain}/docs
- Blog: https://${domain}/blog

# Content Guidelines
- All content is subject to our terms of service
- Attribution required for substantial quotes
- Commercial use requires permission

# Contact
For AI partnership inquiries: contact@${domain}
`;

  return {
    robotsTxt,
    llmsTxt,
  };
}

function generateSummary(score: number, recommendations: Recommendation[]): string {
  const highPriorityCount = recommendations.filter(r => r.priority === 'high').length;
  
  if (score >= 90) {
    return `Excellent! Your site has strong crawler optimization with a score of ${score}/100. ${highPriorityCount === 0 ? 'No critical issues detected.' : `Address ${highPriorityCount} remaining optimization(s) to reach 100.`}`;
  } else if (score >= 70) {
    return `Good foundation with a score of ${score}/100. You have ${highPriorityCount} high-priority optimization(s) that could significantly improve your AI visibility.`;
  } else if (score >= 50) {
    return `Moderate optimization needed (${score}/100). ${highPriorityCount} critical issue(s) are limiting your discoverability by search engines and AI agents.`;
  } else {
    return `Significant improvements needed (${score}/100). Your site is missing essential files that control how AI and search engines interact with your content. ${highPriorityCount} critical action(s) required.`;
  }
}

function analyzeSEOImpact(scan: Scan): SEOImpact {
  const hasSitemap = scan.robotsTxtContent?.toLowerCase().includes('sitemap') ?? false;
  const hasLLMsTxt = scan.llmsTxtFound;
  const hasRobotsTxt = scan.robotsTxtFound;

  return {
    crawlability: hasRobotsTxt 
      ? hasSitemap 
        ? "Excellent - Crawlers can efficiently discover your content"
        : "Good - But missing sitemap reference reduces efficiency"
      : "Poor - No guidance for search engine crawlers",
    
    indexability: hasRobotsTxt
      ? "Controlled - You're managing what gets indexed"
      : "Uncontrolled - Everything is potentially indexed",
    
    aiVisibility: hasLLMsTxt
      ? "Optimized - AI agents have structured guidance about your content"
      : "Limited - Missing the new standard for AI agent communication"
  };
}

function generateCompetitorInsights(scan: Scan): string[] {
  return [
    "75% of top-ranking websites have optimized robots.txt files with sitemap references",
    "Sites with llms.txt see 3x higher citation rates in AI-generated responses",
    "Properly configured bot permissions increase organic traffic by an average of 23%",
    "Early adopters of llms.txt are gaining competitive advantage in AI-powered search"
  ];
}
